server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:erp}
    username: ${POSTGRES_USER:erp}
    password: ${POSTGRES_PASSWORD:erp}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: users
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    schemas: users
    default-schema: users
    locations: classpath:db/migration
app:
  jwt:
    secret: ${APP_JWT_SECRET:dev-secret-please-change-32-chars-minimum-123456}
    access-ttl: 3600
