server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/erp
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: auth
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    schemas: auth
    default-schema: auth
    locations: classpath:db/migration
app:
  jwt:
    secret: f59c84b9e3db679ddc41bfc59bfb8a1ddaf91022cf47bc6b9faef05c2d0e9483
    access-ttl: 3600
