server:
  port: 8080
spring:
  application:
    name: gateway-service
  config:
    import: "classpath:routes/auth.yml,classpath:routes/users.yml,classpath:routes/products.yml,classpath:routes/orders.yml,classpath:routes/sales.yml,classpath:routes/finance.yml,classpath:routes/hrms.yml,classpath:routes/enquiry.yml"
app:
  jwt:
    secret: ${APP_JWT_SECRET:dev-secret-please-change-32-chars-minimum-123456}
    access-ttl: 3600

proxy:
  routes:
    - id: auth
      path: /api/auth/**
      url: http://auth-service:8081
    - id: users
      path: /api/users/**
      url: http://user-service:8082
    - id: products
      path: /api/products/**
      url: http://product-service:8083
    - id: orders
      path: /api/orders/**
      url: http://order-service:8084
    - id: sales
      path: /api/sales/**
      url: http://sales-service:8085
    - id: finance
      path: /api/finance/**
      url: http://finance-service:8086
    - id: hrms
      path: /api/hrms/**
      url: http://hrms-service:8087
    - id: enquiry
      path: /api/enquiry/**
      url: http://enquiry-service:8088
