server:
  port: 8080
spring:
  application:
    name: gateway-service
  # config:
  #   import: "classpath:routes/auth.yml,classpath:routes/users.yml,classpath:routes/products.yml,classpath:routes/orders.yml,classpath:routes/sales.yml,classpath:routes/finance.yml,classpath:routes/hrms.yml,classpath:routes/enquiry.yml,classpath:routes/reports.yml"
app:
  jwt:
    secret: ${APP_JWT_SECRET:dev-secret-please-change-32-chars-minimum-123456}
    access-ttl: 3600

proxy:
  routes:
    - id: auth
      path: /api/auth/**
      uri: lb://auth-service
      stripPrefix: false
    - id: users
      path: /api/users/**
      uri: lb://user-service
      stripPrefix: false
    - id: products
      path: /api/products/**
      uri: lb://product-service
      stripPrefix: false
    - id: orders
      path: /api/orders/**
      uri: lb://order-service
      stripPrefix: false
    - id: sales
      path: /api/sales/**
      uri: lb://sales-service
      stripPrefix: false
    - id: finance
      path: /api/finance/**
      uri: lb://finance-service
      stripPrefix: false
    - id: hrms
      path: /api/hrms/**
      uri: lb://hrms-service
      stripPrefix: false
    - id: enquiry
      path: /api/enquiry/**
      uri: lb://enquiry-service
      stripPrefix: false
    - id: reports
      path: /api/reports/**
      uri: lb://reporting-service
      stripPrefix: true

springdoc:
  swagger-ui:
    display-operation-id: true
    try-it-out-enabled: true
    urls:
      - name: Auth Service
        url: /api/auth/v3/api-docs
      - name: User Service
        url: /api/users/v3/api-docs
      - name: Product Service
        url: /api/products/v3/api-docs
      - name: Order Service
        url: /api/orders/v3/api-docs
      - name: Sales Service
        url: /api/sales/v3/api-docs
      - name: Finance Service
        url: /api/finance/v3/api-docs
      - name: HRMS Service
        url: /api/hrms/v3/api-docs
      - name: Enquiry Service
        url: /api/enquiry/v3/api-docs
      - name: Reporting Service
        url: /api/reports/v3/api-docs
