server:
  port: 8080
spring:
  application:
    name: gateway-service
  config:
    import: "classpath:routes/auth.yml,classpath:routes/users.yml,classpath:routes/products.yml,classpath:routes/orders.yml,classpath:routes/sales.yml,classpath:routes/finance.yml,classpath:routes/hrms.yml,classpath:routes/enquiry.yml,classpath:routes/reports.yml"
app:
  jwt:
    secret: ${APP_JWT_SECRET:dev-secret-please-change-32-chars-minimum-123456}
    access-ttl: 3600

proxy:
  routes:
    - id: auth
      path: /api/auth/**
      url: http://localhost:8081
    - id: users
      path: /api/users/**
      url: http://localhost:8082
    - id: products
      path: /api/products/**
      url: http://localhost:8083
    - id: orders
      path: /api/orders/**
      url: http://localhost:8084
    - id: sales
      path: /api/sales/**
      url: http://localhost:8085
    - id: finance
      path: /api/finance/**
      url: http://localhost:8086
    - id: hrms
      path: /api/hrms/**
      url: http://localhost:8087
    - id: enquiry
      path: /api/enquiry/**
      url: http://localhost:8088
    - id: reports
      path: /api/reports/**
      url: http://localhost:9100
      stripPrefix: true
